#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GymPal.Resource", IsApplication=true)]

namespace GymPal
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int IMG_1039 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int john = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int AllMachinesListView = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int MachineName = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int aboutButton = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int cartButton = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int description = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int listallButton = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int logoImageView = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int machineIcon = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int machineImageView = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int machineName = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int mapButton = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int shortDescription = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int takePictureButton = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListMachines = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MachineDetailView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MachineListRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainMenu = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
